console.log("Object", typeof {})
console.log("Array", typeof [])
console.log("String", typeof "")
console.log("Number", typeof 0)
console.log("BigInt", typeof 0n)
console.log("RegExp", typeof /0/)
console.log("Undefined", typeof undefined)
console.log("Null", typeof null)
console.log("Boolean", typeof true)
console.log("Function", typeof (() => {}))
console.log("Symbol", typeof Symbol())
